[package]
name = "rust-rocket"
version = "0.7.2"
authors = ["Tim Peters <mail@darksecond.nl>", "Lauri Gustafsson <me@gustafla.space>"]
license = "MIT"
description = """
A client implementation of GNU Rocket.
"""
repository = "https://github.com/demoscene-rs/rust-rocket"
edition = "2018"

[dependencies]
byteorder = "1.4.2"
serde = { version = "1.0.120", features = ["derive"]}
thiserror = "1.0.23"

[dev-dependencies]
bincode = "1.3.1"
